allowing templates to be applied AFTER the cluster is fully up
rancherfederal/rke2-ansible pull request #181
Opened 2024-01-10 20:10 UTC by aleiner

## What type of PR is this?

_(REQUIRED)_

- [ ] bug
- [ ] cleanup
- [ ] documentation
- [x] feature

## What this PR does / why we need it:

_(REQUIRED)_

Allows for manifest files to be applied after the cluster is up.  Current functionality only allows for manifests to be applied after the first server node is up.

## Which issue(s) this PR fixes:

_(REQUIRED)_

Fixes #180

2024-01-16 15:34 UTC, mddamato requested changes

2024-01-16 15:34 UTC, mddamato commented on roles/cluster_manifest/vars/main.yml
delete blank file?

2024-01-16 15:34 UTC, mddamato commented on roles/cluster_manifest/defaults/main.yml
> +kubernetes_api_server_host: "{{ hostvars[groups['rke2_servers'][0]].inventory_hostname }}"
unused var?

2024-01-16 15:40 UTC, aleiner commented on roles/cluster_manifest/vars/main.yml
deleted

2024-01-16 15:41 UTC, mddamato approved these changes

2024-01-16 17:14 UTC, merged

2024-03-06 23:14 UTC, jcox10 commented
How is this different than the `add-manifest-addons.yml`? It should be at least documented in `inventory/sample/group_vars/rke2_servers.yml` at the _bare_ minimum.

2024-03-27 13:23 UTC, aleiner commented
@jcox10 - Thanks for keeping us honest. PR has been submitted to address the additional documentation.

We will rework some of the logic before a new release where the variable names may change to make things more streamlined.

2024-03-27 13:55 UTC, mddamato commented
@jcox10 You're correct. please see https://github.com/rancherfederal/rke2-ansible/issues/198